### ISSUE TITLE
get-countries.js throws an error when run locally

### ISSUE THREAD

**Issue by stufinn** [contentful/covid-19-site-template#34]
Whenever I try to run `yarn develop` locally I get the following error message.  I think it's because it's not getting the data that's expected from running `node get-countries.js`.

Would love some help to work through this!

---
yarn run v1.21.1
$ node get-countries.js && gatsby develop
TypeError: Cannot read property '0' of undefined
    at IncomingMessage.<anonymous> (/Users/Stu/Web_Development/Websites/Stop-The-Spread/Iron Range/covid-19-iron-range/get-countries.js:22:35)
    at IncomingMessage.emit (events.js:333:22)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
---

**Comment by Khaledgarbaya** [comment]
Hi @stufinn I think this might be related to missing env vars.
Can you check out this branch and see if it fixes your issue https://github.com/contentful/covid-19-site-template/pull/35

**Comment by stufinn** [comment]
@Khaledgarbaya that fixes it! Runs perfectly now.  Thanks so much

**Comment by Khaledgarbaya** [comment]
PR Merged
